fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^docs/.*$
      - id: trailing-whitespace
        exclude: README.md
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
