fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^docs/.*$
      - id: trailing-whitespace
        exclude: README.md
  - repo: https://github.com/pycqa/flake8
    rev: "7.1.0"
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --no-strict-optional]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
