name: Lint & test
on: [push, pull_request]

jobs:
  linters:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8
        poetry_version: 1.0
        args: install
    - name: Lint with pre-commit
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8
        poetry_version: 1.0
        args: run pre-commit run --all-files
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8
        poetry_version: 1.0
        args: install
    - name: Run matrix of tests with Tox
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8
        poetry_version: 1.0
        args: run tox
